# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name=b'created')),
                ('modified', models.DateTimeField(verbose_name=b'modified')),
                ('make', models.CharField(max_length=50, unique=True, verbose_name=b'Auto Maker')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
