# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 22, 52, 44, 596000), editable=False, verbose_name=b'created'),
        ),
        migrations.AlterField(
            model_name='car',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 22, 52, 44, 596000), verbose_name=b'modified'),
        ),
    ]
