# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseplate', models.CharField(max_length=10)),
                ('cartype', models.CharField(choices=[(b'hda', b'Honda'), (b'tya', b'Toyota'), (b'fd', b'Ford'), (b'jp', b'Jeep'), (b'oth', b'Other')], default=b'oth', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
