# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160225_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinguser',
            options={'verbose_name': 'Parking User', 'verbose_name_plural': 'Parking Users'},
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='cartype',
            field=models.CharField(choices=[(b'hda', b'Honda'), (b'tya', b'Toyota'), (b'fd', b'Ford'), (b'jp', b'Jeep'), (b'oth', b'Other')], default=b'oth', max_length=3, verbose_name=b'Car Type'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='licenseplate',
            field=models.CharField(max_length=10, verbose_name=b'License Plate'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='phonenumber',
            field=models.IntegerField(default=8675309, verbose_name=b'Phone Number'),
        ),
    ]
