# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '__first__'),
        ('app', '0004_auto_20160227_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name=b'created')),
                ('modified', models.DateTimeField(verbose_name=b'modified')),
                ('license_state', models.CharField(choices=[(b'AL', b'Alabama'), (b'AK', b'Alaska'), (b'AZ', b'Arizona'), (b'AR', b'Arkansas'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DE', b'Delaware'), (b'FL', b'Florida'), (b'GU', b'Georgia'), (b'HI', b'Hawaii'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'IA', b'Iowa'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'ME', b'Maine'), (b'MD', b'Maryland'), (b'MA', b'Massachusetts'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MS', b'Mississippi'), (b'MO', b'Missouri'), (b'MT', b'Montana'), (b'NE', b'Nebraska'), (b'NV', b'Nevada'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NY', b'New York'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VT', b'Vermont'), (b'VI', b'Virginia'), (b'WA', b'Washington'), (b'WV', b'West Virginia'), (b'WI', b'Wisconsin'), (b'WY', b'Wyoming')], default=b'CA', max_length=2, verbose_name=b'License State')),
                ('license_plate', models.CharField(max_length=10, verbose_name=b'License Plate')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 22, 45, 41, 427000), editable=False, verbose_name=b'created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 22, 45, 52, 704000), verbose_name=b'modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicles',
            name='parking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ParkingUser'),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='cars',
            field=models.ManyToManyField(through='app.Vehicles', to='car.Car'),
        ),
    ]
