# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160227_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='car',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='parking_user',
        ),
        migrations.RemoveField(
            model_name='parkinguser',
            name='cars',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
