# Generated by Django 2.1.2 on 2018-11-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160227_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinguser',
            name='cartype',
            field=models.CharField(choices=[('hda', 'Honda'), ('tya', 'Toyota'), ('fd', 'Ford'), ('jp', 'Jeep'), ('oth', 'Other')], default='oth', max_length=3, verbose_name='Car Type'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='licenseplate',
            field=models.CharField(max_length=10, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='modified',
            field=models.DateTimeField(verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='phonenumber',
            field=models.IntegerField(default=8675309, verbose_name='Phone Number'),
        ),
    ]
